version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch_estatemetrics
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data-estatemetrics:/usr/share/elasticsearch/data
    ports:
      - "9400:9400"
      - "9500:9500"

volumes:
  elasticsearch-data-estatemetrics:
