name: Backend | Build & Deploy New Docker Image

on:
  workflow_run:
    workflows: ["Update Package Version"]
    types: [completed]

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: packages/backend

      - name: Log read version
        run: echo ${{ steps.package-version.outputs.current-version }}

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker buildx build --platform linux/arm64 -t ghcr.io/${{ github.repository }}/estate-metrics:${{ steps.package-version.outputs.current-version }} --push packages/backend

      - name: Create ~/Docker/estatemetrics
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          password: ${{ secrets.SSH_PASSPHRASE }}
          port: 8362
          script: |
            mkdir -p ~/Docker/estatemetrics

      - name: Copy docker-compose.yml to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 8362
          source: "packages/backend/docker-compose.yml"
          target: "~/Docker/estatemetrics"

      - name: Pull New Image and Restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          password: ${{ secrets.SSH_PASSPHRASE }}
          port: 8362
          script: |
            .rd/bin/docker pull ghcr.io/${{ github.repository }}/estate-metrics:${{ steps.package-version.outputs.current-version }}
            .rd/bin/docker stop estatemetrics ; .rd/bin/docker rm estatemetrics || true
            .rd/bin/docker-compose -f ~/Docker/estatemetrics/docker-compose.yml up -d
