name: Update Package Version

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - "packages/backend/**"

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node v22
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn version to @stable
        run: corepack prepare yarn@stable --activate

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      # NOTE, this probably isnt tuned fully right
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: packages/backend
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: ${{ steps.package-version.outputs.current-version }}
          version-fragment: "bug"
      - name: Update package.json
        working-directory: packages/backend
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          yarn version --patch
          git add package.json
          git commit -m "Bump version to ${{ steps.bump_version.outputs.next-version }}"
          git push
      - name: Create new tag
        working-directory: packages/backend
        run: |
          echo "Current version is ${{ steps.package-version.outputs.current-version }}.\nNext version is ${{ steps.bump_version.outputs.next-version }}"
          git tag ${{ steps.bump_version.outputs.next-version }}
          git push origin ${{ steps.bump_version.outputs.next-version }}
