name: Update Package Version

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - "packages/backend/**"

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: packages/backend
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: ${{ steps.package-version.outputs.current-version }}
          version-fragment: "bug"
      - name: Create new tag
        working-directory: packages/backend
        run: |
          echo "Current version is ${{ steps.package-version.outputs.current-version }}.\nNext version is ${{ steps.bump_version.outputs.next-version }}"
          git tag ${{ steps.bump_version.outputs.next-version }}
          git push origin ${{ steps.bump_version.outputs.next-version }}

      - name: Update package.json
        working-directory: packages/backend
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npm version ${{ steps.bump_version.outputs.next-version }}
          git push
